var emoji = [
    {
      "tts": "flower",
      "unicode": "U+1F469",
      "files": "svg/blume.svg",
      "tags": [],
      "author": "Jane Whatever",
      "sentiment": "neutral",
      "hasSkinTone": "false",
      "hasHairColor": "false",
    },
    {
      "tts": "church",
      "unicode": "U+1F469",
      "files": "svg/kirche.svg",
      "tags": [],
      "author": "Jane Whatever",
      "sentiment": "neutral",
      "hasSkinTone": "false",
      "hasHairColor": "false",
    },
    {
      "tts": "lamp",
      "unicode": "U+1F469",
      "files": "svg/lampe.svg",
      "tags": [],
      "author": "Jane Whatever",
      "sentiment": "neutral",
      "hasSkinTone": "false",
      "hasHairColor": "false",
    },
    {
      "tts": "arrow",
      "unicode": "U+1F469",
      "files": "svg/pfeil.svg",
      "tags": [],
      "author": "Jane Whatever",
      "sentiment": "neutral",
      "hasSkinTone": "false",
      "hasHairColor": "false",
    },
]
